### ISSUE TITLE
Linter reporting errors with valid code

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#6]
I'm getting errors on the lines that contain:  `schedule(2, 0, -1)`, `event("e", 0, 0)`, `kmagnitudes[] = gkmagnitudes` and  `kfrequencies[] = gkfrequencies`

```csound-csd
<CsoundSynthesizer>
<CsInstruments>
nchnls = 2
0dbfs = 1
ksmps = 256
sr = 44100

instr 1

    ilength = 10
    k1 init 0
    if ilength != 0 then
        schedule(2, 0, -1)
    endif

    k1 += 1

    if k1 == ilength - 1 then
        event("e", 0, 0)
    endif

gkmagnitudes[] fillarray 1, 2, 3, 4
gkfrequencies[] fillarray 1, 2, 3, 4

endin

instr 2

    kmagnitudes[] = gkmagnitudes
    kfrequencies[] = gkfrequencies
endin

schedule(1, 0 ,-1)

</CsInstruments>
<CsScore>
</CsScore>
</CsoundSynthesizer>
```

I have tested this csd and it runs fine though.

**Comment by nwhetsell** [comment]
Thanks for reporting this! The issue with `schedule(2, 0, -1)` and `event("e", 0, 0)` should be fixed in 3a6f90c6a5e164776d09990dd42eed4baaceea4e and 0cdc685350ba7865492183dccc83953f0f54a56c. The issue with `kmagnitudes[] = gkmagnitudes` and `kfrequencies[] = gkfrequencies` should be fixed in commit 863558409c038b9d70d360bd0166e19d6214e45d.
