### ISSUE TITLE
Linter not searching using INCDIR for files

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#8]
The linter doesn't seem to be using the INCDIR variable to search for included files, so receiving file not found errors.

**Comment by nwhetsell** [comment]
This has been on the proverbial [to-do](https://github.com/nwhetsell/linter-csound/blob/fbdaa5b49cf6d1261ff0b07d4126e791eceea2cf/lib/csound-parser/preprocessor.jison-lex#L546) list since July 2016, when I switched from parsing Csound output to using Jison.

Here are some things I’ve thought about doing:

1. **Get INCDIR from Csound using [csound-api’s `GetEnv`](https://github.com/nwhetsell/csound-api#GetEnv).** I don’t think this has any chance of working beyond simple cases. Csound’s [`--env`](https://csound.github.io/docs/manual/CommandFlagsCategory.html#FlagsCatMinusEnvEquals) option permits setting (or concatenating to) INCDIR, and this option can be included in a `<CsOptions>` tag. This means that figuring out Csound’s value of INCDIR would require either parsing options in `<CsOptions>` tags, or actually running a Csound performance (which I’m trying to avoid).

2. **Use a .csoundrc file.** I was thinking of using a JSON file to track Csound options, but Csound already uses a [.csoundrc file](https://csound.github.io/docs/manual/CommandUnifileParFile.html), and it’s not JSON. This is another complication that requires parsing Csound options.

3. **Use a simple file of include directories.** This is what [linter-clang](https://github.com/AtomLinter/linter-clang#clang_complete) does.

Option 3 is almost certainly the easiest to implement, and since INCDIR can be changed using Csound’s API, a list of paths may be necessary anyway. (Paths added using Csound’s API may not appear in command line options, so linter-csound has to be told about them.)

**Comment by eddyc** [comment]
Yeah, option 3 does sound the easiest alright, even if there was a field in the atom package options screen to type in paths that would be pretty good but for projects that might set the INCDIR using the API this would obviously not be so robust.
Ed

**Comment by nwhetsell** [comment]
I just published an updated linter-csound with [options for including files](https://github.com/nwhetsell/linter-csound#including-files), if you want to give it a spin.
